version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_container_etl
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${mysql_pass}"
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: my_db
        target: /var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer_container_etl
    restart: always
    ports:
      - 8080:8080
volumes:
  my_db:
