version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_container_etl
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: my_db
        target: /var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer_container_etl
    restart: always
    ports:
      - 8080:8080
volumes:
  my_db:
